### ISSUE TITLE
Globito de fecha se muestra al hacer ctrl+p para imprimir, propuesta de arreglo

### ISSUE THREAD

**Issue by codesthenos** [midudev/minimalist-portfolio-json#49]
Hola midu, esto quiza debria ser una pr, pero soy muy novato aun, usando este repo me he dado cuenta de que al hacer hover en las fechas y haces ctrl+p sale en la impresion el globito que sale al hacer hover, aunque estoy trasladando todos los estilos a tailwind, me ha dado por comporbar si sabria arreglaro, y he probado y funciona incluyendo esta media querie en Exsperience.astro:
```css
@media print {
  [data-title]:after {
    display: none;
  }
}
```
